-- Run once in the Supabase SQL Editor for a project without this table.
-- Intentionally fail if it exists; do not silently reuse unknown grants/policies.
begin;

create table public.reward_requests (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz not null default now(),
  store_name text not null check (char_length(btrim(store_name)) between 1 and 100),
  purchase_date date not null,
  purchase_amount bigint not null check (purchase_amount between 1 and 9007199254740991),
  order_number text check (char_length(order_number) <= 100),
  customer_name text not null check (char_length(btrim(customer_name)) between 1 and 80),
  email text not null check (char_length(email) <= 254 and email ~ '^[^[:space:]@]+@[^[:space:]@.]+([.][^[:space:]@.]+)+$'),
  lightning_destination text not null check (char_length(btrim(lightning_destination)) between 1 and 10000),
  memo text check (char_length(memo) <= 1000),
  status text not null default 'pending'
);

alter table public.reward_requests enable row level security;

-- Revoke Supabase default grants before allowing only the form's input columns.
revoke all privileges on table public.reward_requests from public, anon, authenticated;
grant usage on schema public to anon;
grant insert (
  store_name, purchase_date, purchase_amount, order_number,
  customer_name, email, lightning_destination, memo
) on public.reward_requests to anon;

create policy reward_requests_anon_insert
on public.reward_requests
for insert
to anon
with check (status = 'pending');

-- No SELECT/UPDATE/DELETE policies or grants for public clients.
-- id, created_at and status are generated by the database, not supplied by anon.
commit;
